In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
!ls /content/drive/MyDrive

'01 Niccolò Machiavelli, Selection from The Prince (1).pdf'
'03 William Shakespeare, Hamlet.pdf'
'04 Francis Bacon, Selection from The New Organon.gdoc'
'04 Francis Bacon, Selection from The New Organon.pdf'
'05 René Descartes, Selection from Discourse on Method and Meditations on First Philosophy.pdf'
'1 - Hukuk Kavramı v.2 (1).gslides'
 20210305_140653.m4a
'20211004_153505 (1).m4a'
 20211004_153505.m4a
'2021 Yabancı Dil Bilgisi Seviye Tespit Sınavı.pdf'
'3 post.gdoc'
'AB Tarihçe Çeviri.gdoc'
'AB TARİHÇESİ, KURUM ve KURULUŞLARI (1).gdoc'
'AB TARİHÇESİ, KURUM ve KURULUŞLARI.gdoc'
'AB Terimce.gsheet'
 AB.xls
'Asgari İlk Belgelendirme Tetkik Süresi.gdoc'
'Barbara Assignment 3.gdoc'
 barbara.gdoc
'Bilgi ve Beceriler (1).gdoc'
'Bilgi ve Beceriler.gdoc'
'Cahide sınav.gdoc'
'Can you give me a text version of this:  Argentin....gsheet'
'Colab Notebooks'
'Competence Criteria.gdoc'
 Complexity.gdoc
'Copy of MICROSOFT SUNUM.gslides'
'Copy of W9Neack.pdf'
'CV - Özlem Deniz Kahraman (4).pdf'
'Cybersecurity against the Rising Threat of Cyber Attacks.gdoc'
'Deniz Kahraman explores Smartcat-2020-03-08-export.tmx'
'Devoir 3 TECH.1.docx'
'Devoir 3 TECH.1.docx.docx'
'DOC-20200428-WA0000. (1).gdoc'
 DOC-20200428-WA0000..gdoc
 DOC-20200429-WA0000..gdoc
 DOC-20200531-WA0020..gdoc
 Doktora.gdoc
'EMİNE KÜLKEDİSİ.gdoc'
'EMİNE KÜLKEDİSİ RAPOR (1).gdoc'
'EMİNE KÜLKEDİSİ RAPOR.gdoc'
 Exam.gdoc
'film listesi.gdoc'
'FINAL PROJET FUSUN.gdoc'
'füsun eng-tr-.gdoc'
'füsun metinler.gdoc'
'füsun metinler(tr).gdoc'
'füsun TEKNOLOJI RAPOR MT.gdoc'
'Getting started.pdf'
'Grup 2 Terimce.gsheet'
'Grup 3.gslides'
'Halal product service process and or management system categories.gdoc'
'Hayal Erdoğan - çeviri deneme.docx'
 HIMARS.gdoc
'İş Sektörü İle Karmaşıklık Sınıfları Arasındaki Bağlantıya Örnekler.gdoc'
 KAHRAMAN.docx
'KizBasina Genel Gonulluluk Sozlesmesi_Guncel_2024.docx'
'Lesson 2.mp4'
 maalouf.gslides
 Malta
 MBT.gdoc
'MICROSOFT SUNUM.gslides'
'Minimum Initial Certification Audit Time.gdoc'
'MT sunumu.gdoc'
'NATO nedir?.gdoc'
'Neslihan TOPCU-G20-Çin-Yayın-EN.docx'
'OPED PRESENTATION.gslides'
'Özlem Deniz Kahraman CV ENG.pdf'
'Özlem Deniz KAHRAMAN CV eng.pdf'
'Özlem Deniz Kahraman CV TR (1).pdf'
'Özlem Deniz Kahraman CV TR.pdf'
'Özlem Deniz Kahraman.rtf.gdoc'
'Özlem Deniz Kahraman Yeni Pasaport-pages-deleted_compressed.pdf'
'Possible Interview Questions.gdoc'
'PROJE BD.gslides'
'Projet 1 - Atelier EN-FR.gdoc'
'PROJET-2 (EN-FR) - Ã  la maison.gdoc'
'Proposal-Migration .gdoc'
'Proxy War.gdoc'
'Research on Securitization.gdoc'
 SAMPLES
'Short writing 1 assignment Özlem Deniz Kahraman  (1).docx'
'Short writing 1 assignment Özlem Deniz Kahraman .docx'
 SINAVVV.gsheet
'SIRIN REPORT.gdoc'
'şirin TEKNOLOJİ RAPOR mt.docx[3052].gdoc'
'şirin TEKNOLOJİ RAPOR mt new1 (1).gdoc'
'şirin TEKNOLOJİ RAPOR mt new1.gdoc'
'Sous-titre sunum Fusun.gslides'
'Stephen King.docx'
'Stephen King.gdoc'
'SUBTITLE WORKSHOP.pptx'
'SUNUM TEK. FR 2.gslides'
'Table of Competence Criteria.gdoc'
'TAO FUSUN PROJE.gdoc'
'Teknik Ceviri_terim listesi_02 (1).gsheet'
'Teknik Ceviri_terim listesi_02 (3) (1).gsheet'
'Teknik Ceviri_terim listesi_02 (3) (2).gsheet'
'Teknik Ceviri_terim listesi_02 (3).gsheet'
'Teknik Ceviri_terim listesi_02 (3).xls'
'Teknik Ceviri_terim listesi_02.gsheet'
'Teknik Ceviri_terim listesi_02 Totale.gsheet'
'Teknik Ceviri_terim listesi 2 Dosyasının Kopyası.gsheet'
'Teknik Ceviri terim listesi ENG.gsheet'
'TEKNOLOJİ RAPOR (1).gdoc'
'TEKNOLOJİ RAPOR.docx'
'TEKNOLOJİ RAPOR.gdoc'
 Terimce.gsheet
'TERIM TABLOSU FINAL.gsheet'
'TERMINOLOGY PROJECT.gdoc'
'titanik ödev'
'TRIN 266exercice1.gdoc'
 TRIN266legaltext1docx.gdoc
'TRIN 33201 Translation 56 The Applicant  42721.gdoc'
 TRIN485-FR.gdoc
'Untitled document (1).gdoc'
'Untitled document (2).gdoc'
'Untitled document (3).gdoc'
'Untitled document (4).gdoc'
'Untitled document (5).gdoc'
'Untitled document (6).gdoc'
'Untitled document.gdoc'
'Untitled spreadsheet (1).gsheet'
'Untitled spreadsheet.gsheet'
 video1013941518.mp4
 video1018038825.mp4
 video1382832989.mp4
 video1426687386.mp4
 video1522565157.mp4
 video1638621862.mp4
 video1711496202.mp4
 video1734390590.mp4
 video1852534897.mp4
 video1877890347.mp4
 W9Neack.pdf
'WS FINAL.gdoc'
 YANDEX.TRANSLATE.gslides
 YANDEX.TRANSLATE.pptx
'zjq-sdku-djj - Dec 24, 2021 (1).gjam'
'zjq-sdku-djj - Dec 24, 2021 (1).pdf'
'zjq-sdku-djj - Dec 24, 2021.gjam'
'zjq-sdku-djj - Dec 24, 2021.pdf'

In [15]:
import pandas as pd

file_path = '/content/drive/MyDrive/Colab Notebooks/Titanic_dataset.csv'  # Adjust if your file name is different
df_titanic = pd.read_csv(file_path)

df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
#kazada ölenlerin yaş ortalaması
olen_yas = df_titanic[df_titanic['Survived'] == 0]['Age'].mean()
print("Ölen İnsan Yaş Ortalaması: ", olen_yas)

Ölen İnsan Yaş Ortalaması:  30.62617924528302

In [33]:
# Kazada ölenlerin bilet fiyatlarının ortalamasını ve medyanı
kaza_olenler = df_titanic[df_titanic['Survived'] == 0]
olen_fiyat_ortalama = kaza_olenler['Fare'].mean()
olen_fiyat_medyan = kaza_olenler['Fare'].median()
print("Ortalama:", olen_fiyat_ortalama, " Medyan: ", olen_fiyat_medyan)

Ortalama: 22.117886885245902 Medyan:  10.5

In [40]:
#Ölen erkek yaş ortalama
olen_erkek = df_titanic[(df_titanic['Survived'] == 0) & (df_titanic['Sex'] == 'male')]['Age'].mean()
print("Ölen Erkek Yaş Ortalaması: ", olen_erkek)

Ölen Erkek Yaş Ortalaması:  31.618055555555557

In [41]:
#Ölen kadın yaş ortalama
olen_kadin = df_titanic[(df_titanic['Survived'] == 0) & (df_titanic['Sex'] == 'female')]['Age'].mean()
print("Ölen Kadın Yaş Ortalaması: ", olen_kadin)

Ölen Kadın Yaş Ortalaması:  25.046875

In [42]:
#Kazadan kurtulanların yaş ortalaması
kurtulan_yas = df_titanic[df_titanic['Survived'] == 1]['Age'].mean()
print("Kurtulan İnsan Yaş Ortalaması: ", kurtulan_yas)

Kurtulan İnsan Yaş Ortalaması:  28.343689655172415

In [43]:
#Kazadan kurtulanların bilet fiyatlarının ortalaması
kurtulanlar_bilet_ortalama = df_titanic[df_titanic['Survived'] == 1]['Fare'].mean()
print("Kurtulanların bilet fiyat Ortalaması: ", kurtulanlar_bilet_ortalama)

Kurtulanların bilet fiyat Ortalaması:  48.39540760233918

In [44]:
#Kazadan kurtulan toplam kişi sayısı
kurtulanlar_toplam_kişi = len(df_titanic[df_titanic['Survived'] == 1])
print("Kazadan kurtulan toplam kişi sayısı: ", kurtulanlar_toplam_kişi)

Kazadan kurtulan toplam kişi sayısı:  342

In [45]:
#10 yaşından küçüklerin bilet fiyatlarının medyan değeri
on_yas_bilet_fiyat_ort = df_titanic[df_titanic['Age'] < 10]['Fare'].median()
print("10 yaş bilet fiyat ortalaması: ", on_yas_bilet_fiyat_ort)

10 yaş bilet fiyat ortalaması:  27.0

In [46]:
#1., 2. ve 3. sınıf bilet fiyatlarının ortalama ve medyanlarını karşılaştırınız
df_titanic.groupby('Pclass')['Fare'].agg(['mean', 'median'])

             mean   median
Pclass
1       84.154687  60.2875
2       20.662183  14.2500
3       13.675550   8.0500

In [47]:
#Kazada ölen kadınların oranı ile erkeklerin oranını karşılaştırınız
# Ölen kadın oranı
olen_kadin_orani = len(df_titanic[(df_titanic['Sex'] == 'female') & (df_titanic['Survived'] == 0)]) / len(df_titanic[df_titanic['Sex'] == 'female'])

# Ölen erkek oranı
olen_erkek_orani = len(df_titanic[(df_titanic['Sex'] == 'male') & (df_titanic['Survived'] == 0)]) / len(df_titanic[df_titanic['Sex'] == 'male'])

olen_kadin_orani, olen_erkek_orani

(0.25796178343949044, 0.8110918544194108)